/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/backroom.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} scale={[36.74, 15.29, 23.92]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Tiles} position={[2.63, 1, -2.91]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Tiles} position={[2.64, 1, 2.92]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Walls.002']} position={[5.29, 1, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.Tiles} position={[0, 1, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Walls.006']} position={[9.17, 1, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Walls.007']} position={[14.47, 1, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Walls.008']} position={[11.81, 1, 2.92]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Walls.009']} position={[11.8, 1, -2.91]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Walls.010']} position={[21.49, 1, -2.91]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Walls.011']} position={[21.5, 1, 2.92]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Walls.012']} position={[24.15, 1, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Walls.013']} position={[18.86, 1, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Walls.014']} position={[-33.93, 1, -2.91]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials.Tiles} position={[-33.93, 1, -8.72]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Walls.016']} position={[-22.87, 1, -2.91]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Walls.017']} position={[-22.87, 1, -8.71]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials['Walls.018']} position={[-20.24, 1, -11.63]} rotation={[Math.PI, -0.01, Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['Walls.020']} position={[-20.12, 1, -20.54]} rotation={[-Math.PI, 0.02, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials.Tiles} position={[-28.41, 1, -23.76]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials.Tiles} position={[-33.92, 1, -23.76]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials.Tiles} position={[-17.32, 1, -23.76]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials.Tiles} position={[-22.83, 1, -23.76]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube023.geometry} material={materials.Tiles} position={[-0.64, 1, -23.76]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube024.geometry} material={materials.Tiles} position={[4.88, 1, -23.76]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube025.geometry} material={materials.Tiles} position={[-6.21, 1, -23.76]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube026.geometry} material={materials.Tiles} position={[-6.21, 1, 23.81]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials.Tiles} position={[32.62, 1, -23.76]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube031.geometry} material={materials.Tiles} position={[21.52, 1, -23.76]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube032.geometry} material={materials.Tiles} position={[27.04, 1, 23.81]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials.Tiles} position={[15.95, 1, -23.76]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube034.geometry} material={materials.Tiles} position={[10.43, 1, -23.76]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube028.geometry} material={materials.Tiles} position={[10.43, 1, 23.81]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube030.geometry} material={materials.Tiles} position={[27.04, 1, -23.76]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube035.geometry} material={materials.Tiles} position={[21.52, 1, 23.81]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube036.geometry} material={materials.Tiles} position={[32.62, 1, 23.81]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube037.geometry} material={materials.Tiles} position={[-11.73, 1, -23.76]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube039.geometry} material={materials.Tiles} position={[4.88, 1, 23.81]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube040.geometry} material={materials.Tiles} position={[-0.64, 1, 23.81]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube041.geometry} material={materials.Tiles} position={[-22.83, 1, 23.81]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube042.geometry} material={materials.Tiles} position={[-17.32, 1, 23.81]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube043.geometry} material={materials.Tiles} position={[-28.41, 1, 23.81]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube044.geometry} material={materials.Tiles} position={[-33.92, 1, 23.81]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube045.geometry} material={materials.Tiles} position={[-36.57, 1, 20.89]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube046.geometry} material={materials['Walls.052']} position={[-36.57, 1, 15.37]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube047.geometry} material={materials['Walls.053']} position={[-36.56, 1, 4.28]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube048.geometry} material={materials['Walls.054']} position={[-36.56, 1, 9.8]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube049.geometry} material={materials.Tiles} position={[-36.55, 1, -12.4]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube050.geometry} material={materials.Tiles} position={[-36.54, 1, -17.91]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube051.geometry} material={materials['Walls.057']} position={[-36.55, 1, -6.82]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube052.geometry} material={materials.Tiles} position={[-36.55, 1, -1.31]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube053.geometry} material={materials.Tiles} position={[-36.54, 1, -22.18]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 1.48]} />
      <mesh geometry={nodes.Cube054.geometry} material={materials['Walls.060']} position={[36.61, 1, -22.18]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 1.48]} />
      <mesh geometry={nodes.Cube055.geometry} material={materials.Tiles} position={[36.6, 1, -1.31]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube056.geometry} material={materials.Tiles} position={[36.6, 1, -6.82]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube057.geometry} material={materials.Tiles} position={[36.61, 1, -17.91]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube058.geometry} material={materials.Tiles} position={[36.6, 1, -12.4]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube059.geometry} material={materials.Tiles} position={[36.59, 1, 9.8]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube060.geometry} material={materials.Tiles} position={[36.59, 1, 4.28]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube061.geometry} material={materials.Tiles} position={[36.58, 1, 15.37]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube062.geometry} material={materials.Tiles} position={[36.58, 1, 20.89]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube063.geometry} material={materials['Walls.069']} position={[36.01, 1, -23.76]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 0.63]} />
      <mesh geometry={nodes.Cube064.geometry} material={materials.Tiles} position={[36.01, 1, 23.8]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 0.63]} />
      <mesh geometry={nodes.Cube038.geometry} material={materials['Tiles.001']} position={[-11.73, 1, 23.81]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube029.geometry} material={materials['Tiles.003']} position={[16.01, 1, 23.81]} rotation={[0, 1.57, 0]} scale={[0.13, 1, 2.78]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/backroom.glb')
